
import java.time.LocalDate;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Acer
 */
public class PerhitunganHariFrame extends javax.swing.JFrame {

    /**
     * Creates new form PerhitunganHariFrame
     */
    public PerhitunganHariFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        calendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbBulan = new javax.swing.JComboBox<>();
        spnTahun = new javax.swing.JSpinner();
        btnHitung = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        datePerbandingan = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        jScrollPane1.setViewportView(txtHasil);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        calendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendar1PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 8);
        jPanel1.add(calendar1, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Bulan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Tahun");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(jLabel2, gridBagConstraints);

        cbbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbbBulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbBulanItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(cbbBulan, gridBagConstraints);

        spnTahun.setModel(new javax.swing.SpinnerNumberModel(2024, null, null, 1));
        spnTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTahunStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(spnTahun, gridBagConstraints);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(btnHitung, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Tanggal perbandingan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(datePerbandingan, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbBulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbBulanItemStateChanged
        sinkronkanCalendar();
    }//GEN-LAST:event_cbbBulanItemStateChanged

    private void spnTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTahunStateChanged
        sinkronkanCalendar();
    }//GEN-LAST:event_spnTahunStateChanged

    private void calendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendar1PropertyChange
// Ambil bulan dan tahun dari JCalendar
        int bulan = calendar1.getMonthChooser().getMonth(); // Bulan 0-11
        int tahun = calendar1.getYearChooser().getYear();

        // Set ComboBox bulan dan Spinner tahun sesuai nilai JCalendar
        cbbBulan.setSelectedIndex(bulan);
        spnTahun.setValue(tahun);
    }//GEN-LAST:event_calendar1PropertyChange

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        tampilkanHasil();
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerhitunganHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerhitunganHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerhitunganHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerhitunganHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerhitunganHariFrame().setVisible(true);
            }
        });
    }

    private void sinkronkanCalendar() {
        // Ambil bulan dan tahun dari ComboBox dan Spinner
        int bulan = cbbBulan.getSelectedIndex(); // Januari = 0, Februari = 1, dst.
        int tahun = (int) spnTahun.getValue();

        // Set tanggal di JCalendar berdasarkan bulan dan tahun yang dipilih
        java.util.Calendar cal = calendar1.getCalendar();
        cal.set(java.util.Calendar.YEAR, tahun);
        cal.set(java.util.Calendar.MONTH, bulan);

        // Sinkronkan perubahan ke JCalendar
        calendar1.setCalendar(cal);
    }

    private void tampilkanHasil() {
        // Ambil tanggal yang dipilih di JCalendar
        java.util.Calendar calendar = calendar1.getCalendar();
        int tahun = calendar.get(java.util.Calendar.YEAR);
        int bulan = calendar.get(java.util.Calendar.MONTH) + 1; // JCalendar bulan 0-11, jadi tambahkan 1
        int hari = calendar.get(java.util.Calendar.DAY_OF_MONTH);

        // Buat LocalDate untuk tanggal yang dipilih di JCalendar
        LocalDate date = LocalDate.of(tahun, bulan, hari);

        // Hitung jumlah hari di bulan yang dipilih
        int jumlahHari = date.lengthOfMonth();

        // Cek apakah tahun tersebut kabisat
        boolean isKabisat = date.isLeapYear();

        // Hari pertama di bulan (tanggal 1)
        String hariPertama = date.getDayOfWeek().toString();  // Mengambil nama hari pertama (contoh: MONDAY, TUESDAY, dst)

        // Hari terakhir di bulan
        String hariTerakhir = date.withDayOfMonth(jumlahHari).getDayOfWeek().toString(); // Nama hari terakhir bulan

        // Ambil tanggal dari JDateChooser
        java.util.Date selectedDate = datePerbandingan.getDate();
        if (selectedDate == null) {
            // Jika tidak ada tanggal yang dipilih di JDateChooser
            txtHasil.setText("Silakan pilih tanggal di JDateChooser untuk perbandingan.");
            return;
        }

        // Konversi tanggal yang dipilih dari JDateChooser ke LocalDate
        LocalDate datePerbandinganLocal = selectedDate.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();

        long selisihHari = java.time.temporal.ChronoUnit.DAYS.between(date, datePerbandinganLocal); // Hitung selisih hari

        // Format hasilnya
        String hasil = "Bulan: " + cbbBulan.getSelectedItem() + "\n"
                + "Tahun: " + tahun + "\n"
                + "Jumlah Hari: " + jumlahHari + "\n"
                + (isKabisat ? "Tahun ini adalah tahun kabisat!" : "Tahun ini bukan tahun kabisat.") + "\n"
                + "Hari Pertama: " + hariPertama + "\n"
                + "Hari Terakhir: " + hariTerakhir + "\n"
                + "Selisih Hari: " + Math.abs(selisihHari) + " hari"; // Tampilkan selisih hari

        // Tampilkan hasil ke JTextArea
        txtHasil.setText(hasil);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private com.toedter.calendar.JCalendar calendar1;
    private javax.swing.JComboBox<String> cbbBulan;
    private com.toedter.calendar.JDateChooser datePerbandingan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnTahun;
    private javax.swing.JTextArea txtHasil;
    // End of variables declaration//GEN-END:variables
}
